services:
  - type: web
    name: render_test
    env: elixir
    buildCommand: sh ./build.sh
    startCommand: _build/prod/rel/so_eat/bin/so_eat start
    healthCheckPath: /
    envVars:
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: SOPOST_API_USER
        sync: false
      - key: SOPOST_API_PASSWORD
        sync: false
      - key: GOOGLE_API_KEY
        sync: false